// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.29.3

package com.example.protobuf;

public final class Inventory {
  private Inventory() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Inventory.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code inventory.StockAction}
   */
  public enum StockAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * 입고
     * </pre>
     *
     * <code>IN = 1;</code>
     */
    IN(1),
    /**
     * <pre>
     * 출고
     * </pre>
     *
     * <code>OUT = 2;</code>
     */
    OUT(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        StockAction.class.getName());
    }
    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 입고
     * </pre>
     *
     * <code>IN = 1;</code>
     */
    public static final int IN_VALUE = 1;
    /**
     * <pre>
     * 출고
     * </pre>
     *
     * <code>OUT = 2;</code>
     */
    public static final int OUT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StockAction valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StockAction forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return IN;
        case 2: return OUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StockAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StockAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StockAction>() {
            public StockAction findValueByNumber(int number) {
              return StockAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.protobuf.Inventory.getDescriptor().getEnumTypes().get(0);
    }

    private static final StockAction[] VALUES = values();

    public static StockAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StockAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:inventory.StockAction)
  }

  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:inventory.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 quantity = 3;</code>
     * @return The quantity.
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code inventory.Product}
   */
  public static final class Product extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:inventory.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Product.class.getName());
    }
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.Inventory.internal_static_inventory_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.Inventory.internal_static_inventory_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.Inventory.Product.class, com.example.protobuf.Inventory.Product.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_ = 0;
    /**
     * <code>int32 quantity = 3;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (quantity_ != 0) {
        output.writeInt32(3, quantity_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.Inventory.Product)) {
        return super.equals(obj);
      }
      com.example.protobuf.Inventory.Product other = (com.example.protobuf.Inventory.Product) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.Inventory.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.Inventory.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.Inventory.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.Inventory.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code inventory.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:inventory.Product)
        com.example.protobuf.Inventory.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.Inventory.internal_static_inventory_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.Inventory.internal_static_inventory_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.Inventory.Product.class, com.example.protobuf.Inventory.Product.Builder.class);
      }

      // Construct using com.example.protobuf.Inventory.Product.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        quantity_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.Inventory.internal_static_inventory_Product_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Product getDefaultInstanceForType() {
        return com.example.protobuf.Inventory.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Product build() {
        com.example.protobuf.Inventory.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Product buildPartial() {
        com.example.protobuf.Inventory.Product result = new com.example.protobuf.Inventory.Product(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.Inventory.Product result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.quantity_ = quantity_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.Inventory.Product) {
          return mergeFrom((com.example.protobuf.Inventory.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.Inventory.Product other) {
        if (other == com.example.protobuf.Inventory.Product.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                quantity_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 3;</code>
       * @return The quantity.
       */
      @java.lang.Override
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 3;</code>
       * @param value The quantity to set.
       * @return This builder for chaining.
       */
      public Builder setQuantity(int value) {

        quantity_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quantity_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:inventory.Product)
    }

    // @@protoc_insertion_point(class_scope:inventory.Product)
    private static final com.example.protobuf.Inventory.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.Inventory.Product();
    }

    public static com.example.protobuf.Inventory.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.Inventory.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WarehouseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:inventory.Warehouse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string location = 3;</code>
     * @return The location.
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 3;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code inventory.Warehouse}
   */
  public static final class Warehouse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:inventory.Warehouse)
      WarehouseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Warehouse.class.getName());
    }
    // Use Warehouse.newBuilder() to construct.
    private Warehouse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Warehouse() {
      name_ = "";
      location_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.Inventory.internal_static_inventory_Warehouse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.Inventory.internal_static_inventory_Warehouse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.Inventory.Warehouse.class, com.example.protobuf.Inventory.Warehouse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object location_ = "";
    /**
     * <code>string location = 3;</code>
     * @return The location.
     */
    @java.lang.Override
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 3;</code>
     * @return The bytes for location.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, location_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, location_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.Inventory.Warehouse)) {
        return super.equals(obj);
      }
      com.example.protobuf.Inventory.Warehouse other = (com.example.protobuf.Inventory.Warehouse) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getLocation()
          .equals(other.getLocation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.Inventory.Warehouse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.Inventory.Warehouse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.Warehouse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.Inventory.Warehouse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code inventory.Warehouse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:inventory.Warehouse)
        com.example.protobuf.Inventory.WarehouseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.Inventory.internal_static_inventory_Warehouse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.Inventory.internal_static_inventory_Warehouse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.Inventory.Warehouse.class, com.example.protobuf.Inventory.Warehouse.Builder.class);
      }

      // Construct using com.example.protobuf.Inventory.Warehouse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        location_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.Inventory.internal_static_inventory_Warehouse_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Warehouse getDefaultInstanceForType() {
        return com.example.protobuf.Inventory.Warehouse.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Warehouse build() {
        com.example.protobuf.Inventory.Warehouse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.Warehouse buildPartial() {
        com.example.protobuf.Inventory.Warehouse result = new com.example.protobuf.Inventory.Warehouse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.Inventory.Warehouse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.location_ = location_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.Inventory.Warehouse) {
          return mergeFrom((com.example.protobuf.Inventory.Warehouse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.Inventory.Warehouse other) {
        if (other == com.example.protobuf.Inventory.Warehouse.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                location_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 3;</code>
       * @return The location.
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       * @return The bytes for location.
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        location_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        location_ = getDefaultInstance().getLocation();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        location_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:inventory.Warehouse)
    }

    // @@protoc_insertion_point(class_scope:inventory.Warehouse)
    private static final com.example.protobuf.Inventory.Warehouse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.Inventory.Warehouse();
    }

    public static com.example.protobuf.Inventory.Warehouse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Warehouse>
        PARSER = new com.google.protobuf.AbstractParser<Warehouse>() {
      @java.lang.Override
      public Warehouse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Warehouse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Warehouse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.Inventory.Warehouse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InventoryLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:inventory.InventoryLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.inventory.Product product = 2;</code>
     * @return Whether the product field is set.
     */
    boolean hasProduct();
    /**
     * <code>.inventory.Product product = 2;</code>
     * @return The product.
     */
    com.example.protobuf.Inventory.Product getProduct();
    /**
     * <code>.inventory.Product product = 2;</code>
     */
    com.example.protobuf.Inventory.ProductOrBuilder getProductOrBuilder();

    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     * @return Whether the warehouse field is set.
     */
    boolean hasWarehouse();
    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     * @return The warehouse.
     */
    com.example.protobuf.Inventory.Warehouse getWarehouse();
    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     */
    com.example.protobuf.Inventory.WarehouseOrBuilder getWarehouseOrBuilder();

    /**
     * <code>.inventory.StockAction action = 4;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.inventory.StockAction action = 4;</code>
     * @return The action.
     */
    com.example.protobuf.Inventory.StockAction getAction();

    /**
     * <code>int32 quantity_changed = 5;</code>
     * @return The quantityChanged.
     */
    int getQuantityChanged();

    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code inventory.InventoryLog}
   */
  public static final class InventoryLog extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:inventory.InventoryLog)
      InventoryLogOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        InventoryLog.class.getName());
    }
    // Use InventoryLog.newBuilder() to construct.
    private InventoryLog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InventoryLog() {
      action_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.Inventory.internal_static_inventory_InventoryLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.Inventory.internal_static_inventory_InventoryLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.Inventory.InventoryLog.class, com.example.protobuf.Inventory.InventoryLog.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PRODUCT_FIELD_NUMBER = 2;
    private com.example.protobuf.Inventory.Product product_;
    /**
     * <code>.inventory.Product product = 2;</code>
     * @return Whether the product field is set.
     */
    @java.lang.Override
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.inventory.Product product = 2;</code>
     * @return The product.
     */
    @java.lang.Override
    public com.example.protobuf.Inventory.Product getProduct() {
      return product_ == null ? com.example.protobuf.Inventory.Product.getDefaultInstance() : product_;
    }
    /**
     * <code>.inventory.Product product = 2;</code>
     */
    @java.lang.Override
    public com.example.protobuf.Inventory.ProductOrBuilder getProductOrBuilder() {
      return product_ == null ? com.example.protobuf.Inventory.Product.getDefaultInstance() : product_;
    }

    public static final int WAREHOUSE_FIELD_NUMBER = 3;
    private com.example.protobuf.Inventory.Warehouse warehouse_;
    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     * @return Whether the warehouse field is set.
     */
    @java.lang.Override
    public boolean hasWarehouse() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     * @return The warehouse.
     */
    @java.lang.Override
    public com.example.protobuf.Inventory.Warehouse getWarehouse() {
      return warehouse_ == null ? com.example.protobuf.Inventory.Warehouse.getDefaultInstance() : warehouse_;
    }
    /**
     * <code>.inventory.Warehouse warehouse = 3;</code>
     */
    @java.lang.Override
    public com.example.protobuf.Inventory.WarehouseOrBuilder getWarehouseOrBuilder() {
      return warehouse_ == null ? com.example.protobuf.Inventory.Warehouse.getDefaultInstance() : warehouse_;
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private int action_ = 0;
    /**
     * <code>.inventory.StockAction action = 4;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.inventory.StockAction action = 4;</code>
     * @return The action.
     */
    @java.lang.Override public com.example.protobuf.Inventory.StockAction getAction() {
      com.example.protobuf.Inventory.StockAction result = com.example.protobuf.Inventory.StockAction.forNumber(action_);
      return result == null ? com.example.protobuf.Inventory.StockAction.UNRECOGNIZED : result;
    }

    public static final int QUANTITY_CHANGED_FIELD_NUMBER = 5;
    private int quantityChanged_ = 0;
    /**
     * <code>int32 quantity_changed = 5;</code>
     * @return The quantityChanged.
     */
    @java.lang.Override
    public int getQuantityChanged() {
      return quantityChanged_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getProduct());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getWarehouse());
      }
      if (action_ != com.example.protobuf.Inventory.StockAction.UNKNOWN.getNumber()) {
        output.writeEnum(4, action_);
      }
      if (quantityChanged_ != 0) {
        output.writeInt32(5, quantityChanged_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProduct());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWarehouse());
      }
      if (action_ != com.example.protobuf.Inventory.StockAction.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, action_);
      }
      if (quantityChanged_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantityChanged_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.Inventory.InventoryLog)) {
        return super.equals(obj);
      }
      com.example.protobuf.Inventory.InventoryLog other = (com.example.protobuf.Inventory.InventoryLog) obj;

      if (getId()
          != other.getId()) return false;
      if (hasProduct() != other.hasProduct()) return false;
      if (hasProduct()) {
        if (!getProduct()
            .equals(other.getProduct())) return false;
      }
      if (hasWarehouse() != other.hasWarehouse()) return false;
      if (hasWarehouse()) {
        if (!getWarehouse()
            .equals(other.getWarehouse())) return false;
      }
      if (action_ != other.action_) return false;
      if (getQuantityChanged()
          != other.getQuantityChanged()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (hasProduct()) {
        hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
        hash = (53 * hash) + getProduct().hashCode();
      }
      if (hasWarehouse()) {
        hash = (37 * hash) + WAREHOUSE_FIELD_NUMBER;
        hash = (53 * hash) + getWarehouse().hashCode();
      }
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (37 * hash) + QUANTITY_CHANGED_FIELD_NUMBER;
      hash = (53 * hash) + getQuantityChanged();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.protobuf.Inventory.InventoryLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.protobuf.Inventory.InventoryLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.Inventory.InventoryLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.Inventory.InventoryLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code inventory.InventoryLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:inventory.InventoryLog)
        com.example.protobuf.Inventory.InventoryLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.Inventory.internal_static_inventory_InventoryLog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.Inventory.internal_static_inventory_InventoryLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.Inventory.InventoryLog.class, com.example.protobuf.Inventory.InventoryLog.Builder.class);
      }

      // Construct using com.example.protobuf.Inventory.InventoryLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getProductFieldBuilder();
          getWarehouseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        product_ = null;
        if (productBuilder_ != null) {
          productBuilder_.dispose();
          productBuilder_ = null;
        }
        warehouse_ = null;
        if (warehouseBuilder_ != null) {
          warehouseBuilder_.dispose();
          warehouseBuilder_ = null;
        }
        action_ = 0;
        quantityChanged_ = 0;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.Inventory.internal_static_inventory_InventoryLog_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.InventoryLog getDefaultInstanceForType() {
        return com.example.protobuf.Inventory.InventoryLog.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.InventoryLog build() {
        com.example.protobuf.Inventory.InventoryLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.Inventory.InventoryLog buildPartial() {
        com.example.protobuf.Inventory.InventoryLog result = new com.example.protobuf.Inventory.InventoryLog(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.protobuf.Inventory.InventoryLog result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.product_ = productBuilder_ == null
              ? product_
              : productBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.warehouse_ = warehouseBuilder_ == null
              ? warehouse_
              : warehouseBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.action_ = action_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.quantityChanged_ = quantityChanged_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.Inventory.InventoryLog) {
          return mergeFrom((com.example.protobuf.Inventory.InventoryLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.Inventory.InventoryLog other) {
        if (other == com.example.protobuf.Inventory.InventoryLog.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.hasProduct()) {
          mergeProduct(other.getProduct());
        }
        if (other.hasWarehouse()) {
          mergeWarehouse(other.getWarehouse());
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (other.getQuantityChanged() != 0) {
          setQuantityChanged(other.getQuantityChanged());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getProductFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getWarehouseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                action_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                quantityChanged_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.example.protobuf.Inventory.Product product_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.protobuf.Inventory.Product, com.example.protobuf.Inventory.Product.Builder, com.example.protobuf.Inventory.ProductOrBuilder> productBuilder_;
      /**
       * <code>.inventory.Product product = 2;</code>
       * @return Whether the product field is set.
       */
      public boolean hasProduct() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       * @return The product.
       */
      public com.example.protobuf.Inventory.Product getProduct() {
        if (productBuilder_ == null) {
          return product_ == null ? com.example.protobuf.Inventory.Product.getDefaultInstance() : product_;
        } else {
          return productBuilder_.getMessage();
        }
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public Builder setProduct(com.example.protobuf.Inventory.Product value) {
        if (productBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          product_ = value;
        } else {
          productBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public Builder setProduct(
          com.example.protobuf.Inventory.Product.Builder builderForValue) {
        if (productBuilder_ == null) {
          product_ = builderForValue.build();
        } else {
          productBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public Builder mergeProduct(com.example.protobuf.Inventory.Product value) {
        if (productBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            product_ != null &&
            product_ != com.example.protobuf.Inventory.Product.getDefaultInstance()) {
            getProductBuilder().mergeFrom(value);
          } else {
            product_ = value;
          }
        } else {
          productBuilder_.mergeFrom(value);
        }
        if (product_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public Builder clearProduct() {
        bitField0_ = (bitField0_ & ~0x00000002);
        product_ = null;
        if (productBuilder_ != null) {
          productBuilder_.dispose();
          productBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public com.example.protobuf.Inventory.Product.Builder getProductBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProductFieldBuilder().getBuilder();
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      public com.example.protobuf.Inventory.ProductOrBuilder getProductOrBuilder() {
        if (productBuilder_ != null) {
          return productBuilder_.getMessageOrBuilder();
        } else {
          return product_ == null ?
              com.example.protobuf.Inventory.Product.getDefaultInstance() : product_;
        }
      }
      /**
       * <code>.inventory.Product product = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.protobuf.Inventory.Product, com.example.protobuf.Inventory.Product.Builder, com.example.protobuf.Inventory.ProductOrBuilder> 
          getProductFieldBuilder() {
        if (productBuilder_ == null) {
          productBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.protobuf.Inventory.Product, com.example.protobuf.Inventory.Product.Builder, com.example.protobuf.Inventory.ProductOrBuilder>(
                  getProduct(),
                  getParentForChildren(),
                  isClean());
          product_ = null;
        }
        return productBuilder_;
      }

      private com.example.protobuf.Inventory.Warehouse warehouse_;
      private com.google.protobuf.SingleFieldBuilder<
          com.example.protobuf.Inventory.Warehouse, com.example.protobuf.Inventory.Warehouse.Builder, com.example.protobuf.Inventory.WarehouseOrBuilder> warehouseBuilder_;
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       * @return Whether the warehouse field is set.
       */
      public boolean hasWarehouse() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       * @return The warehouse.
       */
      public com.example.protobuf.Inventory.Warehouse getWarehouse() {
        if (warehouseBuilder_ == null) {
          return warehouse_ == null ? com.example.protobuf.Inventory.Warehouse.getDefaultInstance() : warehouse_;
        } else {
          return warehouseBuilder_.getMessage();
        }
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public Builder setWarehouse(com.example.protobuf.Inventory.Warehouse value) {
        if (warehouseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          warehouse_ = value;
        } else {
          warehouseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public Builder setWarehouse(
          com.example.protobuf.Inventory.Warehouse.Builder builderForValue) {
        if (warehouseBuilder_ == null) {
          warehouse_ = builderForValue.build();
        } else {
          warehouseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public Builder mergeWarehouse(com.example.protobuf.Inventory.Warehouse value) {
        if (warehouseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            warehouse_ != null &&
            warehouse_ != com.example.protobuf.Inventory.Warehouse.getDefaultInstance()) {
            getWarehouseBuilder().mergeFrom(value);
          } else {
            warehouse_ = value;
          }
        } else {
          warehouseBuilder_.mergeFrom(value);
        }
        if (warehouse_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public Builder clearWarehouse() {
        bitField0_ = (bitField0_ & ~0x00000004);
        warehouse_ = null;
        if (warehouseBuilder_ != null) {
          warehouseBuilder_.dispose();
          warehouseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public com.example.protobuf.Inventory.Warehouse.Builder getWarehouseBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWarehouseFieldBuilder().getBuilder();
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      public com.example.protobuf.Inventory.WarehouseOrBuilder getWarehouseOrBuilder() {
        if (warehouseBuilder_ != null) {
          return warehouseBuilder_.getMessageOrBuilder();
        } else {
          return warehouse_ == null ?
              com.example.protobuf.Inventory.Warehouse.getDefaultInstance() : warehouse_;
        }
      }
      /**
       * <code>.inventory.Warehouse warehouse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.example.protobuf.Inventory.Warehouse, com.example.protobuf.Inventory.Warehouse.Builder, com.example.protobuf.Inventory.WarehouseOrBuilder> 
          getWarehouseFieldBuilder() {
        if (warehouseBuilder_ == null) {
          warehouseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.protobuf.Inventory.Warehouse, com.example.protobuf.Inventory.Warehouse.Builder, com.example.protobuf.Inventory.WarehouseOrBuilder>(
                  getWarehouse(),
                  getParentForChildren(),
                  isClean());
          warehouse_ = null;
        }
        return warehouseBuilder_;
      }

      private int action_ = 0;
      /**
       * <code>.inventory.StockAction action = 4;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.inventory.StockAction action = 4;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        action_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.StockAction action = 4;</code>
       * @return The action.
       */
      @java.lang.Override
      public com.example.protobuf.Inventory.StockAction getAction() {
        com.example.protobuf.Inventory.StockAction result = com.example.protobuf.Inventory.StockAction.forNumber(action_);
        return result == null ? com.example.protobuf.Inventory.StockAction.UNRECOGNIZED : result;
      }
      /**
       * <code>.inventory.StockAction action = 4;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(com.example.protobuf.Inventory.StockAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.inventory.StockAction action = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000008);
        action_ = 0;
        onChanged();
        return this;
      }

      private int quantityChanged_ ;
      /**
       * <code>int32 quantity_changed = 5;</code>
       * @return The quantityChanged.
       */
      @java.lang.Override
      public int getQuantityChanged() {
        return quantityChanged_;
      }
      /**
       * <code>int32 quantity_changed = 5;</code>
       * @param value The quantityChanged to set.
       * @return This builder for chaining.
       */
      public Builder setQuantityChanged(int value) {

        quantityChanged_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity_changed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuantityChanged() {
        bitField0_ = (bitField0_ & ~0x00000010);
        quantityChanged_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:inventory.InventoryLog)
    }

    // @@protoc_insertion_point(class_scope:inventory.InventoryLog)
    private static final com.example.protobuf.Inventory.InventoryLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.Inventory.InventoryLog();
    }

    public static com.example.protobuf.Inventory.InventoryLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InventoryLog>
        PARSER = new com.google.protobuf.AbstractParser<InventoryLog>() {
      @java.lang.Override
      public InventoryLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InventoryLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryLog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.Inventory.InventoryLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_Warehouse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_Warehouse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_InventoryLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_inventory_InventoryLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inventory.proto\022\tinventory\"5\n\007Product\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010quantity\030\003 " +
      "\001(\005\"7\n\tWarehouse\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001" +
      "(\t\022\020\n\010location\030\003 \001(\t\"\275\001\n\014InventoryLog\022\n\n" +
      "\002id\030\001 \001(\005\022#\n\007product\030\002 \001(\0132\022.inventory.P" +
      "roduct\022\'\n\twarehouse\030\003 \001(\0132\024.inventory.Wa" +
      "rehouse\022&\n\006action\030\004 \001(\0162\026.inventory.Stoc" +
      "kAction\022\030\n\020quantity_changed\030\005 \001(\005\022\021\n\ttim" +
      "estamp\030\006 \001(\003*+\n\013StockAction\022\013\n\007UNKNOWN\020\000" +
      "\022\006\n\002IN\020\001\022\007\n\003OUT\020\002B,\n\024com.example.protobu" +
      "fZ\024com/example/protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inventory_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", });
    internal_static_inventory_Warehouse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_Warehouse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_Warehouse_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", });
    internal_static_inventory_InventoryLog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventory_InventoryLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_inventory_InventoryLog_descriptor,
        new java.lang.String[] { "Id", "Product", "Warehouse", "Action", "QuantityChanged", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
