// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: inventory.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockAction int32

const (
	StockAction_UNKNOWN StockAction = 0
	StockAction_IN      StockAction = 1 // 입고
	StockAction_OUT     StockAction = 2 // 출고
)

// Enum value maps for StockAction.
var (
	StockAction_name = map[int32]string{
		0: "UNKNOWN",
		1: "IN",
		2: "OUT",
	}
	StockAction_value = map[string]int32{
		"UNKNOWN": 0,
		"IN":      1,
		"OUT":     2,
	}
)

func (x StockAction) Enum() *StockAction {
	p := new(StockAction)
	*p = x
	return p
}

func (x StockAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockAction) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_proto_enumTypes[0].Descriptor()
}

func (StockAction) Type() protoreflect.EnumType {
	return &file_inventory_proto_enumTypes[0]
}

func (x StockAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockAction.Descriptor instead.
func (StockAction) EnumDescriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Warehouse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type InventoryLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product         *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Warehouse       *Warehouse             `protobuf:"bytes,3,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	Action          StockAction            `protobuf:"varint,4,opt,name=action,proto3,enum=inventory.StockAction" json:"action,omitempty"`
	QuantityChanged int32                  `protobuf:"varint,5,opt,name=quantity_changed,json=quantityChanged,proto3" json:"quantity_changed,omitempty"`
	Timestamp       int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryLog) Reset() {
	*x = InventoryLog{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryLog) ProtoMessage() {}

func (x *InventoryLog) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryLog.ProtoReflect.Descriptor instead.
func (*InventoryLog) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryLog) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryLog) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *InventoryLog) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

func (x *InventoryLog) GetAction() StockAction {
	if x != nil {
		return x.Action
	}
	return StockAction_UNKNOWN
}

func (x *InventoryLog) GetQuantityChanged() int32 {
	if x != nil {
		return x.QuantityChanged
	}
	return 0
}

func (x *InventoryLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"I\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"K\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\xf9\x01\n" +
	"\fInventoryLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\aproduct\x18\x02 \x01(\v2\x12.inventory.ProductR\aproduct\x122\n" +
	"\twarehouse\x18\x03 \x01(\v2\x14.inventory.WarehouseR\twarehouse\x12.\n" +
	"\x06action\x18\x04 \x01(\x0e2\x16.inventory.StockActionR\x06action\x12)\n" +
	"\x10quantity_changed\x18\x05 \x01(\x05R\x0fquantityChanged\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp*+\n" +
	"\vStockAction\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02IN\x10\x01\x12\a\n" +
	"\x03OUT\x10\x02B,\n" +
	"\x14com.example.protobufZ\x14com/example/protobufb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_proto_goTypes = []any{
	(StockAction)(0),     // 0: inventory.StockAction
	(*Product)(nil),      // 1: inventory.Product
	(*Warehouse)(nil),    // 2: inventory.Warehouse
	(*InventoryLog)(nil), // 3: inventory.InventoryLog
}
var file_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.InventoryLog.product:type_name -> inventory.Product
	2, // 1: inventory.InventoryLog.warehouse:type_name -> inventory.Warehouse
	0, // 2: inventory.InventoryLog.action:type_name -> inventory.StockAction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
